services:

  nginx:
    container_name: llm_dev_nginx
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  api:
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 

  worker:
    volumes:
      - .:/app

  stream_worker:
    volumes:
      - .:/app
